<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function selectCategoryParent($parentMultilangue, $locale)
    {
        return $this->createQueryBuilder('c')
            ->leftJoin('c.parentMultilangue', 'cp')
            ->where('cp.id = :id and c.locale = :locale')
            ->setParameter('id', $parentMultilangue)
            ->setParameter('locale', $locale)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function selectCategoryParentMultilangue($id, $locale)
    {
        return $this->createQueryBuilder('c')
            ->select('COUNT(c.id)')
            ->leftJoin('c.parentMultilangue', 'cp')
            ->where('cp.id = :id and c.locale != :locale')
            ->setParameter('id', $id)
            ->setParameter('locale', $locale)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function selectCategoryLocaleActive($localeActive)
    {
        return $this->createQueryBuilder('c')
            ->where('c.locale = :localeActive')
            ->setParameter('localeActive', $localeActive);
    }

    public function getTotalCategories($locale)
    {
        return $this->createQueryBuilder('c')
            ->select('COUNT(c) AS TOTAL')
            ->andWhere('c.locale = :locale')
            ->setParameter('locale', $locale)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
