<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function selectCategoryParent($parentMultilangue)
    {
        return $this->createQueryBuilder('c')
            ->leftJoin('c.parentMultilangue', 'cp')
            ->where('cp.id = :id')
            ->setParameter('id', $parentMultilangue)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
