<?php

namespace AppBundle\Repository;

/**
 * ContentsNavRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentsNavRepository extends \Doctrine\ORM\EntityRepository
{
}
