<?php

namespace AppBundle\Repository;

/**
 * ContentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $locale
     * @param null $type
     * @param null $status
     * @param null $category
     *
     * @return mixed
     */
    public function getTotalRegisters($locale, $type = null, $status = null, $category = null)
    {
        $post = ($type) ? $type : 'post';
        $page = ($type) ? $type : 'page';

        $published = ($status) ? $status : true;
        $unpublished = ($status) ? $status : false;

        $qb = $this->createQueryBuilder('c')
            ->select('COUNT(c) AS TOTAL')
            ->where('(c.type = :post or c.type = :page) and (c.status = :published or c.status = :unpublished)')
            ->andWhere('c.locale = :locale')
            ->setParameter('post', $post)
            ->setParameter('page', $page)
            ->setParameter('published', $published)
            ->setParameter('unpublished', $unpublished)
            ->setParameter('locale', $locale)
        ;

        if ($category) {
            $qb->andWhere('c.category = :category')
                ->setParameter('category', $category)
            ;
        }

        return $qb->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @param $offset
     * @param $sizePage
     * @param $locale
     * @param null $type
     * @param null $status
     * @param null $category
     *
     * @return mixed
     */
    public function getResultsPaginated($offset, $sizePage, $locale, $type = null, $status = null, $category = null)
    {
        $post = ($type) ? $type : 'post';
        $page = ($type) ? $type : 'page';

        $published = ($status) ? $status : true;
        $unpublished = ($status) ? $status : false;

        $qb = $this->createQueryBuilder('c')
            ->where('(c.type = :post or c.type = :page) and (c.status = :published or c.status = :unpublished)')
            ->andWhere('c.locale = :locale')
            ->setParameter('post', $post)
            ->setParameter('page', $page)
            ->setParameter('published', $published)
            ->setParameter('unpublished', $unpublished)
            ->setParameter('locale', $locale)
            ->orderBy('c.publishedAt', 'DESC')
            ->setFirstResult($offset)
            ->setMaxResults($sizePage)
        ;

        if ($category) {
            $qb->andWhere('c.category = :category')
                ->setParameter('category', $category)
            ;
        }

        return $qb->getQuery()
            ->execute();
    }

    public function findBySlugIfContentIsPublished($slug)
    {
        return $this->createQueryBuilder('c')
            ->where('c.status = :status and c.slug = :slug')
            ->setParameter('status', true)
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function selectPagesLocaleActive($localeActive)
    {
        return $this->createQueryBuilder('c')
            ->where('c.locale = :localeActive and c.type = :type and c.status = :status')
            ->setParameter('localeActive', $localeActive)
            ->setParameter('type', 'page')
            ->setParameter('status', true);
    }

    public function selectContentParent($parentMultilangue, $locale, $type)
    {
        return $this->createQueryBuilder('c')
            ->leftJoin('c.parentMultilangue', 'cp')
            ->where('cp.id = :id and c.locale = :locale and c.type = :type')
            ->setParameter('id', $parentMultilangue)
            ->setParameter('locale', $locale)
            ->setParameter('type', $type)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
