<?php

namespace AppBundle\Repository;

/**
 * NavRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavRepository extends \Doctrine\ORM\EntityRepository
{
}
