<?php

namespace AppBundle\Repository;

/**
 * NavRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavRepository extends \Doctrine\ORM\EntityRepository
{
    public function removeTranslationNavByIdElement($nav)
    {
        return $this->createQueryBuilder('nav')
            ->where('nav.parentMultilangue = :nav and nav.locale = :locale')
            ->setParameter('nav', $nav['id'])
            ->setParameter('locale', $nav['localeTranslation'])
            ->getQuery()
            ->getOneOrNullResult();
    }
}
