<?php

namespace AppBundle\Repository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends \Doctrine\ORM\EntityRepository
{
    /*public function getProfile($id)
    {
        return $this->createQueryBuilder('p')
                ->select('p, us')
                ->join('p.user', 'us')
                ->where('p.user = :id')
                ->setParameter('id', $id)
                ->getQuery()
                ->getResult();
    }*/
}
